version: "3"
#=============================================================================
# DEV-TOOLS INFRASTRUCTURE & DEPLOYMENT WORKFLOWS
# Focus: Docker lifecycle, remote deployment, health validation
# Requires: task >=3.35, docker, docker compose, ssh, pwsh (Windows)
#=============================================================================

env:
  DEPLOY_DIR: deploy
  DROPLET_IP: 45.55.173.72
  DROPLET_PATH: /opt/Dev-Tools

tasks:
  default:
    desc: Show available infrastructure commands
    silent: true
    cmds:
      - task --list

  #============================================================================
  # BUILD & REGISTRY
  #============================================================================

  build:all:
    desc: Build all service images locally
    summary: |
      Builds orchestrator, gateway, RAG, and state services using
      docker-compose.yml definitions. Uses cache for faster builds.
      The orchestrator contains LangGraph agent nodes (feature-dev,
      code-review, infrastructure, cicd, documentation).
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose build

  build:push-dockerhub:
    desc: Push images to Docker Hub (apscolabs/dev-tools-*)
    summary: |
      Tags and pushes all Dev-Tools images to Docker Hub registry under
      apscolabs organization. Requires Docker Hub authentication.
    cmds:
      - pwsh -File ./support/scripts/deploy/push-dockerhub.ps1

  build:push-docr:
    desc: Push images to DigitalOcean Container Registry
    summary: |
      Tags and pushes all images to DigitalOcean Container Registry.
      Requires doctl authentication and DOCR repository setup.
    cmds:
      - pwsh -File ./support/scripts/deploy/push-docr.ps1

  #============================================================================
  # LOCAL STACK LIFECYCLE
  #============================================================================

  local:up:
    desc: Start full local stack with health checks
    summary: |
      Starts all Docker services in detached mode, waits 15 seconds for
      initialization, then runs health checks on all services.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose up -d
      - '{{if eq OS "windows"}}pwsh -NoProfile -Command "Start-Sleep -Seconds 15"{{else}}sleep 15{{end}}'
      - task: health:local

  local:down:
    desc: Stop and clean up local stack
    summary: |
      Stops all services, removes orphaned containers, and prunes unused
      Docker builder cache. Safe for regular development use.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down --remove-orphans
      - docker builder prune -f

  local:rebuild:
    desc: Rebuild all images and restart stack
    summary: |
      Nuclear rebuild: stops services, rebuilds all images without cache,
      starts stack, and runs health checks. Use when dependencies change.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down
      - docker compose build --no-cache
      - docker compose up -d
      - task: health:local

  local:logs:
    desc: Stream logs from all services (Ctrl+C to exit)
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose logs -f --tail=50

  local:ps:
    desc: Show running services and their ports
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose ps

  local:clean:
    desc: Nuclear cleanup - remove all containers, volumes, images
    summary: |
      ⚠️  DESTRUCTIVE: Removes all containers, volumes, images, networks, and
      build cache. This will delete ALL local data including databases.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down -v
      - docker system prune --all --volumes --force
      - '{{if eq OS "windows"}}pwsh -NoProfile -Command "Write-Host ''Cleanup complete'' -ForegroundColor Green"{{else}}echo "✅ Cleanup complete"{{end}}'

  #============================================================================
  # HEALTH & VALIDATION
  #============================================================================

  health:local:
    desc: Check health of local services (ports 8000-8008)
    summary: |
      Checks /health endpoints for all 9 services on localhost. Reports
      status with check indicators. Use after 'up' or 'rebuild'.
    cmds:
      - '{{if eq OS "windows"}}powershell -NoProfile -ExecutionPolicy Bypass -File ./support/scripts/validation/health-check-local.ps1{{else}}bash ./support/scripts/validation/health-check-local.sh{{end}}'

  health:remote:
    desc: Check health of droplet services
    summary: |
      Checks /health endpoints for all 9 services on droplet (45.55.173.72).
      Use after deployment to verify successful startup.
    cmds:
      - '{{if eq OS "windows"}}pwsh -File ./support/scripts/validation/health-check-remote.ps1 -DropletIP {{.DROPLET_IP}}{{else}}bash ./support/scripts/validation/health-check-remote.sh {{.DROPLET_IP}}{{end}}'

  #============================================================================
  # REMOTE DEPLOYMENT (DROPLET)
  #============================================================================

  deploy:droplet:
    desc: Deploy to DigitalOcean droplet (git pull + rebuild + health)
    summary: |
      Full deployment workflow: SSH to droplet, pull latest code, rebuild
      all images, restart services, wait 20s, then run remote health checks.
    cmds:
      - echo "Deploying to {{.DROPLET_IP}}..."
      - ssh root@{{.DROPLET_IP}} "cd {{.DROPLET_PATH}} && git pull origin main && cd deploy && docker compose down --remove-orphans && docker builder prune -f && docker compose build && docker compose up -d"
      - '{{if eq OS "windows"}}pwsh -NoProfile -Command "Start-Sleep -Seconds 20"{{else}}sleep 20{{end}}'
      - task: health:remote

  deploy:docr:
    desc: Deploy pre-built DOCR images to droplet (no rebuild)
    summary: |
      Fast deployment: pulls pre-built images from DOCR and restarts services
      on droplet. Skips rebuild step. Requires prior build:push-docr.
    cmds:
      - pwsh -File ./deploy-to-droplet.ps1

  deploy:restart:
    desc: Restart services on droplet without rebuild
    summary: |
      Quick restart of all services on droplet using existing images.
      Useful for applying environment variable changes.
    cmds:
      - ssh root@{{.DROPLET_IP}} "cd {{.DROPLET_PATH}}/deploy && docker compose restart"
      - task: health:remote

  #============================================================================
  # DROPLET ADMIN
  #============================================================================

  droplet:ssh:
    desc: SSH into droplet
    summary: Opens SSH session to production droplet as root user.
    interactive: true
    cmds:
      - ssh root@{{.DROPLET_IP}}

  droplet:status:
    desc: Show droplet stack status and disk usage
    summary: |
      Comprehensive droplet status report: running services, disk usage,
      current git branch, and latest commit. Quick health overview.
    cmds:
      - echo "Droplet Status ({{.DROPLET_IP}}):"
      - ssh root@{{.DROPLET_IP}} "cd {{.DROPLET_PATH}}/deploy && echo '=== Docker Services ===' && docker compose ps && echo '' && echo '=== Disk Usage ===' && df -h /opt && echo '' && echo '=== Git Branch ===' && cd .. && git branch --show-current && git log -1 --oneline"

  #============================================================================
  # UTILITIES
  #============================================================================

  utilities:env:
    desc: Show required environment variables status
    summary: |
      Validates config/env/.env file and reports which required variables
      are configured. Checks for Gradient, LangSmith, and Linear keys.
    cmds:
      - '{{if eq OS "windows"}}pwsh -File ./support/scripts/validation/check-env.ps1{{else}}bash ./support/scripts/validation/check-env.sh{{end}}'

  utilities:ports:
    desc: Show port mappings and service URLs
    summary: |
      Reference guide showing all service port mappings (8000-8008, 9090)
      and their purposes. Useful for debugging connectivity issues.
    cmds:
      - |
        echo "Service Port Mappings:"
        echo "  8000 → gateway-mcp (MCP tool routing)"
        echo "  8001 → orchestrator (LangGraph multi-agent workflows)"
        echo "  8007 → rag-context (vector search)"
        echo "  8008 → state-persistence (workflow DB)"
        echo "  9090 → prometheus (metrics)"
        echo ""
        echo "LangGraph Agent Nodes (internal to orchestrator):"
        echo "  - feature-dev (code generation)"
        echo "  - code-review (PR analysis)"
        echo "  - infrastructure (Docker/K8s)"
        echo "  - cicd (pipeline automation)"
        echo "  - documentation (docs generation)"

  #============================================================================
  # WORKFLOW MANAGEMENT (HITL)
  #============================================================================

  workflow:init-db:
    desc: Initialize approval_requests table in PostgreSQL
    summary: |
      Applies approval_requests.sql schema to the devtools database.
      Idempotent - safe to run multiple times. Requires running postgres service.
    cmds:
      - pwsh -File ./support/scripts/workflow/init-approval-schema.ps1

  workflow:list-pending:
    desc: List pending approval requests
    summary: |
      Shows all pending approval requests with risk levels, timeouts, and
      descriptions. Use to see what workflows are waiting for approval.
    cmds:
      - pwsh -File ./support/scripts/workflow/list-pending-approvals.ps1

  workflow:approve:
    desc: Approve a pending request (usage - task workflow:approve REQUEST_ID=<uuid>)
    summary: |
      Approve a specific approval request by UUID. Workflow will resume
      execution after approval. Requires approver role authorization.

      Example: task workflow:approve REQUEST_ID=abc-123-def-456
    requires:
      vars: [REQUEST_ID]
    cmds:
      - pwsh -File ./support/scripts/workflow/approve-request.ps1 -RequestId "{{.REQUEST_ID}}"

  workflow:reject:
    desc: Reject a pending request (usage - task workflow:reject REQUEST_ID=<uuid> REASON="...")
    summary: |
      Reject a specific approval request with reason. Workflow will be
      terminated and agent will be notified of rejection.

      Example: task workflow:reject REQUEST_ID=abc-123 REASON="Security concerns"
    requires:
      vars: [REQUEST_ID, REASON]
    cmds:
      - pwsh -File ./support/scripts/workflow/reject-request.ps1 -RequestId "{{.REQUEST_ID}}" -Reason "{{.REASON}}"

  workflow:status:
    desc: Show status of specific workflow (usage - task workflow:status WORKFLOW_ID=<id>)
    summary: |
      Display detailed status of a workflow including all subtasks, approval
      requests, and execution history.

      Example: task workflow:status WORKFLOW_ID=deploy-auth-123
    requires:
      vars: [WORKFLOW_ID]
    cmds:
      - pwsh -File ./support/scripts/workflow/workflow-status.ps1 -WorkflowId "{{.WORKFLOW_ID}}"

  workflow:clean-expired:
    desc: Clean up expired approval requests
    summary: |
      Marks all expired approval requests as 'expired' status and logs
      cleanup actions. Runs as maintenance task.
    cmds:
      - pwsh -File ./support/scripts/workflow/clean-expired-approvals.ps1

  #============================================================================
  # WORKFLOW EXECUTION (12-Factor Agents)
  #============================================================================

  workflow:pr-deploy:
    desc: Execute PR deployment workflow
    summary: |
      Run full PR deployment workflow: review → test → deploy → approve
      
      Usage:
        task workflow:pr-deploy PR_NUMBER=123 BRANCH=feature/auth
    vars:
      PR_NUMBER: '{{.PR_NUMBER}}'
      BRANCH: '{{.BRANCH}}'
      WORKFLOW_ID: 'pr-deploy-{{.PR_NUMBER}}-{{now | date "20060102-150405"}}'
    cmds:
      - |
        curl -X POST http://localhost:8001/workflow/execute \
          -H "Content-Type: application/json" \
          -d '{
            "workflow_id": "{{.WORKFLOW_ID}}",
            "template": "templates/pr-deployment.workflow.yaml",
            "context": {
              "pr_number": {{.PR_NUMBER}},
              "branch": "{{.BRANCH}}",
              "repo_url": "git@github.com:appsmithery/dev-tools.git"
            }
          }'
      - echo "Workflow started with ID from response"
      - echo "Monitor at http://localhost:8001/workflow/status/"

  workflow:hotfix:
    desc: Execute emergency hotfix workflow (fast-track)
    vars:
      BRANCH: '{{.BRANCH}}'
      ISSUE_ID: '{{.ISSUE_ID}}'
    cmds:
      - |
        curl -X POST http://localhost:8001/workflow/execute \
          -H "Content-Type: application/json" \
          -d '{
            "workflow_id": "hotfix-{{.ISSUE_ID}}-{{now | date "20060102-150405"}}",
            "template": "hotfix.workflow.yaml",
            "context": {
              "branch": "{{.BRANCH}}",
              "issue_id": "{{.ISSUE_ID}}",
              "priority": "urgent"
            }
          }'

  workflow:status:
    desc: Check workflow status
    vars:
      WORKFLOW_ID: '{{.WORKFLOW_ID}}'
    cmds:
      - curl -s http://localhost:8001/workflow/status/{{.WORKFLOW_ID}} | jq .

  workflow:list-templates:
    desc: List available workflow templates
    cmds:
      - cmd: powershell "Get-ChildItem agent_orchestrator/workflows/templates/*.workflow.yaml | Select-Object -ExpandProperty Name"
        platforms: [windows]
      - cmd: ls -1 agent_orchestrator/workflows/templates/*.workflow.yaml | xargs -n1 basename
        platforms: [linux, darwin]

  #============================================================================
  # AGENT PROMPT MANAGEMENT
  #============================================================================

  prompts:validate:
    desc: Validate all agent prompt files
    cmds:
      - |
        for prompt in agent_orchestrator/prompts/*.prompt.md; do
          echo "Validating: $prompt"
          # Check for required sections
          grep -q "## Role" "$prompt" || echo "  ❌ Missing Role section"
          grep -q "## Context Window Budget" "$prompt" || echo "  ❌ Missing Context Budget"
          grep -q "## Output Format" "$prompt" || echo "  ✅ Valid"
        done

  prompts:token-count:
    desc: Estimate token count for agent prompts
    cmds:
      - |
        for prompt in agent_orchestrator/prompts/*.prompt.md; do
          words=$(wc -w < "$prompt")
          tokens=$((words * 4 / 3))  # Rough estimate: 1.33 tokens per word
          echo "$(basename $prompt): ~$tokens tokens"
        done