version: "3"
#=============================================================================
# DEV-TOOLS INFRASTRUCTURE & DEPLOYMENT WORKFLOWS
# Focus: Docker lifecycle, remote deployment, health validation
#=============================================================================

set:
  - pipefail

vars:
  DEPLOY_DIR: deploy
  DROPLET_IP: 45.55.173.72
  DROPLET_PATH: /opt/Dev-Tools

tasks:
  default:
    desc: Show available infrastructure commands
    cmds:
      - task --list

  #============================================================================
  # LOCAL STACK LIFECYCLE
  #============================================================================

  local_deploy:up:
    desc: Start full local stack with health checks
    summary: |
      Starts all Docker services in detached mode, waits 15 seconds for
      initialization, then runs health checks on all services.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose up -d
      - echo "⏳ Waiting 15s for initialization..."
      - sleep 15
      - task: health:local

  local_deploy:down:
    desc: Stop and clean up local stack
    summary: |
      Stops all services, removes orphaned containers, and prunes unused
      Docker builder cache. Safe for regular development use.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down --remove-orphans
      - docker builder prune -f

  local_deploy:rebuild:
    desc: Rebuild all images and restart stack
    summary: |
      Nuclear rebuild: stops services, rebuilds all images without cache,
      starts stack, and runs health checks. Use when dependencies change.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down
      - docker compose build --no-cache
      - docker compose up -d
      - task: health:local

  local_deploy:logs:
    desc: Stream logs from all services (Ctrl+C to exit)
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose logs -f --tail=50

  local_deploy:ps:
    desc: Show running services and their ports
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose ps

  local_deploy:clean:
    desc: Nuclear cleanup - remove all containers, volumes, images
    summary: |
      ⚠️  DESTRUCTIVE: Removes all containers, volumes, images, networks, and
      build cache. This will delete ALL local data including databases.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose down -v
      - docker system prune --all --volumes --force
      - echo "✅ Cleanup complete"

  #============================================================================
  # BUILD & REGISTRY
  #============================================================================

  build:local:
    desc: Build all agent images locally
    summary: |
      Builds all 6 agent images plus gateway, RAG, and state services using
      docker-compose.yml definitions. Uses cache for faster builds.
    dir: "{{.DEPLOY_DIR}}"
    cmds:
      - docker compose build

  build:push_docker_hub:
    desc: Push images to Docker Hub (apscolabs/dev-tools-*)
    summary: |
      Tags and pushes all Dev-Tools images to Docker Hub registry under
      apscolabs organization. Requires Docker Hub authentication.
    cmds:
      - pwsh ./support/scripts/deploy/push-dockerhub.ps1

  build:push_docr:
    desc: Push images to DigitalOcean Container Registry
    summary: |
      Tags and pushes all images to DigitalOcean Container Registry.
      Requires doctl authentication and DOCR repository setup.
    cmds:
      - pwsh ./support/scripts/deploy/push-docr.ps1

  #============================================================================
  # REMOTE DEPLOYMENT (DROPLET)
  #============================================================================

  prod_deploy:droplet:
    desc: Deploy to DigitalOcean droplet (git pull + rebuild + health)
    summary: |
      Full deployment workflow: SSH to droplet, pull latest code, rebuild
      all images, restart services, wait 20s, then run remote health checks.
    cmds:
      - echo "🚀 Deploying to {{.DROPLET_IP}}..."
      - ssh root@{{.DROPLET_IP}} "cd {{.DROPLET_PATH}} && git pull origin main && cd deploy && docker compose down --remove-orphans && docker builder prune -f && docker compose build && docker compose up -d"
      - echo "⏳ Waiting 20s for services to start..."
      - powershell -Command "Start-Sleep -Seconds 20"
      - task: health:remote

  prod_deploy:docr:
    desc: Deploy pre-built DOCR images to droplet (no rebuild)
    summary: |
      Fast deployment: pulls pre-built images from DOCR and restarts services
      on droplet. Skips rebuild step. Requires prior push:docr.
    cmds:
      - pwsh ./deploy-to-droplet.ps1

  prod_deploy:restart:
    desc: Restart services on droplet without rebuild
    summary: |
      Quick restart of all services on droplet using existing images.
      Useful for applying environment variable changes.
    cmds:
      - ssh root@{{.DROPLET_IP}} "cd {{.DROPLET_PATH}}/deploy && docker compose restart"
      - task: health:remote

  #============================================================================
  # HEALTH & VALIDATION
  #============================================================================

  health:local:
    desc: Check health of local services (ports 8000-8008)
    summary: |
      Checks /health endpoints for all 9 services on localhost. Reports
      status with ✅/❌ indicators. Use after 'up' or 'rebuild'.
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./support/scripts/validation/health-check-local.ps1

  health:remote:
    desc: Check health of droplet services
    summary: |
      Checks /health endpoints for all 9 services on droplet (45.55.173.72).
      Use after deployment to verify successful startup.
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./support/scripts/validation/health-check-remote.ps1 -DropletIP {{.DROPLET_IP}}

  health:trace:
    desc: Validate LangSmith tracing is working
    summary: |
      Runs validation script to test LangSmith tracing integration. Checks
      environment variables and makes test LLM call to generate trace.
    cmds:
      - bash ./support/scripts/validation/validate-tracing.sh
      - echo "📊 View traces at https://smith.langchain.com"

  #============================================================================
  # DROPLET ADMIN
  #============================================================================

  droplet:connect_ssh:
    desc: SSH into droplet
    summary: Opens SSH session to production droplet as root user.
    cmds:
      - ssh root@{{.DROPLET_IP}}

  droplet:check_status:
    desc: Show droplet stack status and disk usage
    summary: |
      Comprehensive droplet status report: running services, disk usage,
      current git branch, and latest commit. Quick health overview.
    cmds:
      - echo "📊 Droplet Status ({{.DROPLET_IP}}):"
      - ssh root@{{.DROPLET_IP}} "cd {{.DROPLET_PATH}}/deploy && echo '=== Docker Services ===' && docker compose ps && echo '' && echo '=== Disk Usage ===' && df -h /opt && echo '' && echo '=== Git Branch ===' && cd .. && git branch --show-current && git log -1 --oneline"

  droplet:backup:
    desc: Backup droplet volumes to local machine
    summary: |
      Creates timestamped backup of all Docker volumes from droplet and
      downloads to local ./backups/ directory via SCP.
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./support/scripts/admin/backup-volumes.ps1 -DropletIP {{.DROPLET_IP}} -DropletPath {{.DROPLET_PATH}}

  #============================================================================
  # UTILITIES
  #============================================================================

  utilities:env:
    desc: Show required environment variables status
    summary: |
      Validates config/env/.env file and reports which required variables
      are configured. Checks for Gradient, LangSmith, and Linear keys.
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./support/scripts/validation/check-env.ps1

  utilities:ports:
    desc: Show port mappings and service URLs
    summary: |
      Reference guide showing all service port mappings (8000-8008, 9090)
      and their purposes. Useful for debugging connectivity issues.
    cmds:
      - echo "🔌 Service Port Mappings:"
      - echo "  8000 → gateway-mcp (MCP tool routing)"
      - echo "  8001 → orchestrator (task delegation)"
      - echo "  8002 → feature-dev (code generation)"
      - echo "  8003 → code-review (PR analysis)"
      - echo "  8004 → infrastructure (Docker/K8s)"
      - echo "  8005 → cicd (pipeline automation)"
      - echo "  8006 → documentation (docs generation)"
      - echo "  8007 → rag-context (vector search)"
      - echo "  8008 → state-persistence (workflow DB)"
      - echo "  9090 → prometheus (metrics)"
