version: "3"

vars:
  EXTENSION_NAME: vscode-devtools-copilot
  EXTENSION_VERSION: 0.1.0

tasks:
  install:
    desc: Install extension dependencies
    cmds:
      - npm install
    dir: extensions/vscode-devtools-copilot

  compile:
    desc: Compile TypeScript to JavaScript
    cmds:
      - npx tsc -p .
    dir: extensions/vscode-devtools-copilot
    sources:
      - src/**/*.ts
      - tsconfig.json
    generates:
      - out/**/*.js

  watch:
    desc: Watch for changes and recompile automatically
    cmds:
      - npx tsc -watch -p .
    dir: extensions/vscode-devtools-copilot

  lint:
    desc: Run ESLint on TypeScript files
    cmds:
      - npx eslint src --ext ts
    dir: extensions/vscode-devtools-copilot

  lint:fix:
    desc: Auto-fix ESLint issues
    cmds:
      - npx eslint src --ext ts --fix
    dir: extensions/vscode-devtools-copilot

  test:
    desc: Run extension tests
    cmds:
      - npm run test
    dir: extensions/vscode-devtools-copilot

  package:
    desc: Package extension as VSIX file
    cmds:
      - npx vsce package
    dir: extensions/vscode-devtools-copilot
    deps:
      - compile

  install-local:
    desc: Install extension locally for testing
    cmds:
      - code --install-extension {{.EXTENSION_NAME}}-{{.EXTENSION_VERSION}}.vsix
    dir: extensions/vscode-devtools-copilot
    deps:
      - package

  uninstall-local:
    desc: Uninstall local extension
    cmds:
      - code --uninstall-extension appsmithery.{{.EXTENSION_NAME}}

  dev:
    desc: Run extension in debug mode (opens Extension Development Host)
    cmds:
      - code --extensionDevelopmentPath={{.PWD}}/extensions/vscode-devtools-copilot

  publish:
    desc: Publish to VS Code Marketplace
    cmds:
      - npx vsce publish
    dir: extensions/vscode-devtools-copilot
    deps:
      - package
    preconditions:
      - sh: test -n "$VSCE_TOKEN"
        msg: "VSCE_TOKEN environment variable must be set"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf out/
      - rm -f *.vsix
    dir: extensions/vscode-devtools-copilot

  clean:all:
    desc: Clean build artifacts and node_modules
    cmds:
      - rm -rf out/
      - rm -rf node_modules/
      - rm -f *.vsix
    dir: extensions/vscode-devtools-copilot

  health:
    desc: Check orchestrator health
    cmds:
      - curl -s http://45.55.173.72:8001/health | jq .

  tools:
    desc: List available MCP tools
    cmds:
      - curl -s http://45.55.173.72:8000/tools | jq '.tools | length'

  version:
    desc: Show current version
    cmds:
      - echo "{{.EXTENSION_NAME}} v{{.EXTENSION_VERSION}}"
