version: "3"

# CI/CD Agent - Pipeline generation and deployment orchestration
# Endpoints: POST /generate, POST /deploy, GET /status/{id}

vars:
  AGENT_NAME: cicd
  AGENT_PORT: 8005
  AGENT_HOST:
    sh: echo "${AGENT_HOST:-http://localhost}"

tasks:
  health:
    desc: Check CI/CD service health
    cmds:
      - curl -f {{.AGENT_HOST}}:{{.AGENT_PORT}}/health

  dev:run:
    desc: Run CI/CD agent locally (development mode)
    dir: .
    cmds:
      - python main.py
    env:
      PORT: "{{.AGENT_PORT}}"
      LOG_LEVEL: debug

  dev:test:
    desc: Run CI/CD unit tests
    dir: .
    cmds:
      - pytest tests/ -v

  generate:
    desc: Generate CI/CD pipeline (default GitHub Actions)
    cmds:
      - echo "Generating pipeline..."

  deploy:
    desc: Execute deployment workflow
    cmds:
      - echo "Deploying..."

  build:
    desc: Build CI/CD container image
    dir: ../../containers/cicd
    cmds:
      - docker build -t devtools/cicd:latest .

  logs:
    desc: Tail CI/CD container logs
    dir: ../../compose
    cmds:
      - docker compose logs -f cicd
