version: "3"

# Orchestrator Agent - Task routing and workflow coordination
# Endpoints: POST /orchestrate, GET /tasks/{id}, GET /agents

vars:
  AGENT_NAME: orchestrator
  AGENT_PORT: 8001
  AGENT_HOST:
    sh: echo "${AGENT_HOST:-http://localhost}"

tasks:
  health:
    desc: Check orchestrator service health
    cmds:
      - curl -f {{.AGENT_HOST}}:{{.AGENT_PORT}}/health

  dev:run:
    desc: Run orchestrator locally (development mode)
    dir: .
    cmds:
      - python main.py
    env:
      PORT: "{{.AGENT_PORT}}"
      LOG_LEVEL: debug

  dev:test:
    desc: Run orchestrator unit tests
    dir: .
    cmds:
      - pytest tests/ -v

  list-agents:
    desc: List available specialist agents
    cmds:
      - curl -f {{.AGENT_HOST}}:{{.AGENT_PORT}}/agents

  build:
    desc: Build orchestrator container image
    dir: ../../containers/orchestrator
    cmds:
      - docker build -t devtools/orchestrator:latest .

  logs:
    desc: Tail orchestrator container logs
    dir: ../../compose
    cmds:
      - docker compose logs -f orchestrator
