version: "3"

includes: {}

tasks:
  update:
    desc: Regenerate documentation indices and chatmode stubs
    deps:
      - task: index
      - task: chatmodes:sync

  index:
    desc: Generate the master documentation index under docs/indices/
    cmds:
      - node scripts/docs/generate-index.mjs

  validate:
    desc: Verify documentation index is up to date
    cmds:
      - node scripts/docs/generate-index.mjs --check

  chatmodes:sync:
    desc: Sync chatmode stubs with the current agent roster
    cmds:
      - node scripts/docs/sync-chatmodes.mjs
