version: "3"

includes: {}

tasks:
  sync:
    desc: Rebuild the aggregated reports index (reports/reports-index.json)
    cmds:
      - node scripts/reports/build-index.mjs

  clean:
    desc: Remove transient report artifacts (reports/temp, reports/context/tmp)
    cmds:
      - node scripts/reports/clean.mjs
