version: "3"

includes: {}

vars:
  compose_file: '{{default "compose/docker-compose.yml" .COMPOSE_FILE}}'
  compose_cmd: '{{default "docker compose" .COMPOSE_CMD}}'
  python_bin: '{{default "python" .PYTHON}}'

tasks:
  init:
    desc: Bootstrap dependencies and environment for local development
    deps:
      - task: dependency:install
      - task: env:seed

  dependency:install:
    desc: Install Node.js dependencies
    cmds:
      - npm install

  env:seed:
    desc: Ensure local environment file exists based on .env.example
    cmds:
      - node scripts/tasks/env-seed.mjs

  code-quality:
    desc: Run lightweight static checks across Python services and Docker config
    deps:
      - task: python:compile
      - task: docker:config

  python:compile:
    desc: Byte-compile Python agents to verify syntax
    cmds:
      - "{{.python_bin}} -m compileall agents services"

  docker:config:
    desc: Validate docker-compose configuration
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} config"

  build:
    desc: Build all containers with docker compose
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} build"

  services:up:
    desc: Start the full Dev-Tools stack
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} up -d"

  services:down:
    desc: Stop all running services
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} down"

  services:restart:
    desc: Restart the compose stack
    cmds:
      - task toolchain:services:down
      - task toolchain:services:up

  services:logs:
    desc: Tail logs for all services
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} logs --tail=200"

  services:logs:agent:
    desc: "Tail logs for a specific agent (usage: task toolchain:services:logs:agent -- AGENT=orchestrator)"
    requires:
      vars:
        - AGENT
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} logs -f {{.AGENT}}"

  services:ps:
    desc: Show status for running services
    cmds:
      - "{{.compose_cmd}} -f {{.compose_file}} ps"
