version: "3"

# Documentation Agent - README, API docs, and architecture diagrams
# Endpoints: POST /generate, GET /templates

vars:
  AGENT_NAME: documentation
  AGENT_PORT: 8006
  AGENT_HOST:
    sh: echo "${AGENT_HOST:-http://localhost}"

tasks:
  health:
    desc: Check documentation service health
    cmds:
      - curl -f {{.AGENT_HOST}}:{{.AGENT_PORT}}/health

  dev:run:
    desc: Run documentation agent locally (development mode)
    dir: .
    cmds:
      - python main.py
    env:
      PORT: "{{.AGENT_PORT}}"
      LOG_LEVEL: debug

  dev:test:
    desc: Run documentation unit tests
    dir: .
    cmds:
      - pytest tests/ -v

  generate:
    desc: Generate documentation (default README)
    cmds:
      - echo "Generating documentation..."

  templates:
    desc: List available documentation templates
    cmds:
      - curl -f {{.AGENT_HOST}}:{{.AGENT_PORT}}/templates

  build:
    desc: Build documentation container image
    dir: ../../containers/documentation
    cmds:
      - docker build -t devtools/documentation:latest .

  logs:
    desc: Tail documentation container logs
    dir: ../../compose
    cmds:
      - docker compose logs -f documentation
