version: "3"

includes: {}

vars:
  dev_agents: orchestrator,feature-dev,code-review,documentation
  prod_agents: gateway,orchestrator,feature-dev,code-review,documentation,cicd,infrastructure,rag

tasks:
  _health:
    internal: true
    requires:
      vars:
        - AGENTS
    cmds:
      - node scripts/tasks/agent-health.mjs {{.AGENTS}}

  dev-workflow:test:
    desc: "Run health checks across orchestrator, feature-dev, code-review, and documentation agents"
    deps:
      - task: _health
        vars:
          AGENTS: "{{.dev_agents}}"

  observability:status:
    desc: Show Docker Compose service status for the agent suite
    cmds:
      - task toolchain:services:ps

  observability:logs:
    desc: Tail orchestrator logs for live debugging
    cmds:
      - task toolchain:services:logs:agent -- AGENT=orchestrator

  production-ops:test:e2e:
    desc: "Run an end-to-end health sweep across gateway, orchestrator, and all core agents"
    deps:
      - task: _health
        vars:
          AGENTS: "{{.prod_agents}}"

  system-architect:audit:
    desc: Verify core configuration files and schema assets are present
    cmds:
      - node scripts/tasks/system-audit.mjs
